<script>
            document.getElementById("groupId1").
            addEventListener("click",function(){
                document.location.href="home.html";
            });
            document.getElementById("groupId2").
            addEventListener("click",function(){
                document.location.href="Gallery.html";
            });
            document.getElementById("groupId3").
            addEventListener("click",function(){
                document.location.href="shop.html";
            });
            document.getElementById("groupId4").
            addEventListener("click",function(){
                document.location.href="feedback.html";
            });
            document.getElementById("groupId5").
            addEventListener("click",function(){
                document.location.href="home.html";
            });
            
            document.getElementById("groupId7").
            addEventListener("click",function(){
                document.location.href="Article:1.html";
            });
            document.getElementById("groupId8").
            addEventListener("click",function(){
                document.location.href="Article:2.html";
            });
            document.getElementById("groupId9").
            addEventListener("click",function(){
                document.location.href="Article:3.html";
            });
            document.getElementById("groupId10").
            addEventListener("click",function(){
                document.location.href="Reduce Pollution.html";
            });
            document.getElementById("groupId11").
            addEventListener("click",function(){
                document.location.href="profile.html";
            });
        </script>
